UMI-Gripper
google-deepmind/mujoco_menagerie pull request #106
Opened 2024-10-29 18:16 UTC by omarrayyann

This PR adds the [UMI Gripper](https://umi-gripper.github.io) model. Feel free to suggest any suggestions to improve the quality of the model. The SolidWorks files were first exported to URDFs by [@abanesjo](https://github.com/Abanesjo).

**Model Screenshot:**

<img width="600" alt="umi_gripper" src="https://github.com/user-attachments/assets/c0923689-7600-4ac1-87d3-d1667548ae10">

**Model Video with Objects:**

https://github.com/user-attachments/assets/44f5642d-90c1-409a-9339-156b9a0f0bbb

**Possible Improvements:**
- Adding support for two mirrors.  Otherwise, the one currently added mirror will need to be removed.

2024-10-30 20:25 UTC, kevinzakka requested changes
Great initial PR, left some comments!

2024-10-30 20:25 UTC, kevinzakka commented on umi_gripper/assets/.DS_Store
Remove.

2024-10-30 20:25 UTC, kevinzakka commented on umi_gripper/assets/base_link.STL
@omarrayyann Can you lowercase all the extensions? Some operating systems are case sensitive so we strive to be consistent across models to prevent possible bugs.

2024-10-30 20:25 UTC, kevinzakka commented on umi_gripper/main.py
Not needed.

2024-10-30 20:25 UTC, kevinzakka commented on umi_gripper/scene.xml
> +<?xml version="1.0"?>
Can you remove this line

2024-10-30 20:25 UTC, kevinzakka commented on umi_gripper/umi_gripper.xml
> +  <option integrator="implicitfast" impratio="1" cone="elliptic" noslip_iterations="2">
Maybe @yuvaltassa can comment, but I think either use elliptic + higher impratio (say 10 or 100) or use `noslip_iterations`.

2024-10-30 20:25 UTC, kevinzakka commented on umi_gripper/umi_gripper.xml
> +  <compiler angle="radian" meshdir="assets/" texturedir="assets/" />
Minor nit, can you remove the forward slash at the end of the meshdir and texturedir?

2024-10-30 20:25 UTC, kevinzakka commented on umi_gripper/umi_gripper.xml
> +
Nit: Remove whitespace between last section and </mujoco>.

2024-10-30 20:25 UTC, kevinzakka commented on umi_gripper/umi_gripper.xml
> +      <body name="finger_holder_left" quat="0.707105 0.707108 0 0">
Nit: Use unnormalized quats and let MuJoCo deal with normalization.

`quat=".7 .7 0 0"` --> `quat="1 1 0 0"`

2024-10-30 20:25 UTC, kevinzakka commented on umi_gripper/umi_gripper.xml
> +        rgba="0 0 0 1" material="mirror" contype="0" conaffinity="0" />
Can you make a default class for collisions and one for visual (add the contype=conaffnity=0) and use them here? See other menagerie models for more information.

2024-10-30 20:25 UTC, kevinzakka commented on umi_gripper/umi_gripper.xml
> +    <body pos='0 0 0' euler="-1.571 0 0">
* Remove pos='0 0 0' (it's the default)
* Change euler to quat for consistency if possible.

2024-10-30 20:25 UTC, kevinzakka commented on umi_gripper/umi_gripper.xml
> +      <body name="camera" pos="0 -0.092 0.005" euler="3.14 0 0.0">
The pos and euler attributes can be put in the <camera> tag directly. Do you want an explicit camera body? If not, I think you should merge.

2024-10-30 23:26 UTC, omarrayyann commented
I added the license from the original design [here](https://github.com/real-stanford/universal_manipulation_interface/blob/main/LICENSE).

2024-10-31 00:12 UTC, kevinzakka commented on umi_gripper/umi_gripper.xml
> +    <mesh name="base_link" file="base_link.stl" />
BTW name is not necessary when it matches the file name. So you can remove it if you want a cleaner XML.

2024-11-06 20:19 UTC, kevinzakka commented
Hi @omarrayyann, things got delayed due to CoRL. We'll get to this next week at the latest, thanks again for your contribution!

2024-11-20 18:19 UTC, kevinzakka approved these changes

2025-01-06 21:40 UTC, omarrayyann commented
@saran-t following up on this

2025-01-21 19:12 UTC, kevinzakka approved these changes

2025-01-22 18:48 UTC, yuvaltassa approved these changes

2025-01-23 19:17 UTC, merged