Add missing shoulder aruco
google-deepmind/mujoco_menagerie pull request #26
Opened 2023-10-06 02:36 UTC by hello-chintan

This PR adds the missing shoulder aruco tag on Hello Robot's Stretch robot. The pose of link_aruco_shoulder is eyeballed for now, so I recommend checking the CAD to insert the pin point accurate values.

Before:
![Screenshot from 2023-10-05 19-31-12](https://github.com/google-deepmind/mujoco_menagerie/assets/97639181/611d5523-6499-445e-9b67-2d5b61f56312)

After:
![Screenshot from 2023-10-05 19-30-08](https://github.com/google-deepmind/mujoco_menagerie/assets/97639181/b2b63c0f-017f-44d9-bfe6-151739a8bc68)

2023-10-06 03:39 UTC, kevinzakka commented
Hi @hello-chintan, looks like this aruco tag slipped from the initial conversion process. I actually know the exact values. I'll leave a review comment for you to fix and then I can merge the PR.

2023-10-06 03:42 UTC, kevinzakka requested changes

2023-10-06 03:42 UTC, kevinzakka commented on hello_robot_stretch/stretch.xml
> +        </body>
Remove.

2023-10-06 03:42 UTC, kevinzakka commented on hello_robot_stretch/stretch.xml
Can you add the following body definition [right here](https://github.com/google-deepmind/mujoco_menagerie/blob/main/hello_robot_stretch/stretch.xml#L335) (i.e. the last body in `link_lift`).

```
        <body name="link_aruco_shoulder" pos="-0.0133769 0.0558541 0.0865" quat="1 0 0 0">
          <geom material="Aruco_Shoulder_Sticker" mesh="link_aruco_shoulder" class="visual" mass="3.6E-06"
            shellinertia="true"/>
          <geom mesh="link_aruco_shoulder" class="collision"/>
        </body>
```

2023-10-06 03:55 UTC, kevinzakka commented
Hi @hello-chintan, left some review comments.

2023-10-06 17:52 UTC, yuvaltassa approved these changes

2023-10-06 18:00 UTC, hello-chintan commented on hello_robot_stretch/stretch.xml
Done!

2023-10-06 18:08 UTC, kevinzakka approved these changes

2023-10-10 19:28 UTC, saran-t approved these changes

2023-10-10 20:33 UTC, merged

2023-10-10 20:37 UTC, kevinzakka commented
Merged, thanks @hello-chintan!